project:
  type: website
  render:
    - README.md
    - notebooks/*.ipynb

website:
  title: "moll docs"
  page-navigation: true
  sidebar:
    contents:
      - README.md
      - section: "Diversity"
        contents:
          - notebooks/diversity.ipynb
          - notebooks/chembl-1-percent.ipynb
    tools:
      - icon: github
        url: https://github.com/vsheg/moll

format:
  html:
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 300px
