project:
  type: website
  render:
    - README.md
    - notebooks/
    - reference/

website:
  title: "moll docs"
  repo-url: https://github.com/vsheg/moll
  repo-actions: [issue]
  page-navigation: true
  navbar:
    background: light
    right:
      - text: Examples
        href: notebooks/
      - text: API
        href: reference/
  sidebar:
    contents:
      - README.md
      - section: "Diversity"
        contents:
          - notebooks/diversity.ipynb
          - notebooks/chembl-1-percent.ipynb
          - notebooks/zinc20.ipynb
    tools:
      - icon: github
        url: https://github.com/vsheg/moll

metadata-files:
  - _sidebar.yml

quartodoc:
  package: moll
  parser: google
  style: pkgdown
  sidebar: _sidebar.yml
  dynamic: true
  options:
    include_imports: true
    include_attributes: true
    include_classes: true
    include_functions: true
    children: separate

  sections:
    - title: Pickers
      contents:
        - name: pick
    - title: Utils
      contents:
        - utils

format:
  html:
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 300px
    code-tools:
      source: repo
