project:
  type: website
  render:
    - README.md
    - notebooks/*.ipynb

website:
  title: "moll docs"
  repo-url: https://github.com/vsheg/moll
  repo-actions: [issue]
  page-navigation: true
  sidebar:
    contents:
      - README.md
      - section: "Diversity"
        contents:
          - notebooks/diversity.ipynb
          - notebooks/chembl-1-percent.ipynb
          - notebooks/zinc20.ipynb
    tools:
      - icon: github
        url: https://github.com/vsheg/moll

format:
  html:
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 300px
    code-tools:
      source: repo
