[tool.poetry]
name = "moll"
version = "0.1.3"
description = ""
authors = ["Vsevolod O. Shegolev <v@sheg.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
seaborn = "^0.12.2"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.4"
pytest = "^7.3.2"
jax = "^0.4.12"
jaxlib = {version = "^0.4.12", source = "jax_cpu"}
rdkit = "^2023.3.1"
ipykernel = "^6.25.2"
ipython = "^8.15.0"
autopep8 = "^2.0.4"
rich = "^13.5.3"

[[tool.poetry.source]]
name = "jax_cpu"
url = "https://storage.googleapis.com/jax-releases/jax_releases.html"
priority = "primary"


[[tool.poetry.source]]
name = "jax_cuda"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
priority = "primary"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"