name: Tests on PR to main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 10 * * 1'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    environment: build
    steps:
      - uses: actions/checkout@v4
      - run: pipx install 'poetry==${{ vars.TARGET_POETRY_VERSION }}'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - run: poetry env use ${{ matrix.python-version }}
      - run: poetry install --with cpu,dev
      - run: poetry run pytest
