name: Tests on push

on:
  push:
    branches-ignore: [main] # it has its own workflow
    paths:
      - 'moll/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - run: pipx install 'poetry==${{ vars.TARGET_POETRY_VERSION }}'
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ vars.TARGET_PYTHON_VERSION }}'
          cache: poetry
      - run: poetry env use '${{ vars.TARGET_PYTHON_VERSION }}'
      - run: poetry install
      - run: poetry run pytest