name: Release package to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - run: pipx install 'poetry==${{ vars.TARGET_POETRY_VERSION }}'
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ vars.TARGET_PYTHON_VERSION }}"
          cache: poetry
      - run: poetry install --with jax_cpu
      - run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: release
      url: https://pypi.org/p/moll
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

